# src/tools/shale_tool.py
"""泥质含量解释工具：包含策略构建与解释执行两个原子能力。"""

import pandas as pd
import numpy as np
import json
import glob
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, Tuple

from common.config_loader import ensure_dirs, extract_json_from_response
from llm.caller import load_agent


def _get_curves(params: Dict) -> Dict[str, str]:
    return params.get("curve_names", {
        "GR": "GR", "CGR": "CGR", "DEN": "DEN", "CNL": "CNL",
        "AC": "AC", "PE": "PE", "LAYER": "LAYER", "SH": "SH"
    })


def load_and_preprocess_data(folder_path: str, params: Dict) -> pd.DataFrame:
    print("--- 步骤1: 加载并预处理所有井的原始测井曲线 ---")
    all_files = glob.glob(os.path.join(folder_path, '*.txt'))
    if not all_files:
        raise FileNotFoundError(f"数据目录 '{folder_path}' 中未找到txt文件。")

    curve_names = _get_curves(params)
    gr_col, cgr_col, den_col, cnl_col, ac_col, pe_col, layer_col = (
        curve_names["GR"], curve_names["CGR"], curve_names["DEN"],
        curve_names["CNL"], curve_names["AC"], curve_names["PE"],
        curve_names["LAYER"]
    )

    df_list = []
    for f in all_files:
        well_name = os.path.splitext(os.path.basename(f))[0]
        df = pd.read_csv(f, header=0, skiprows=[1], sep=',')
        df['LOG_ID_FROM_FILENAME'] = well_name
        df_list.append(df)
    combined_df = pd.concat(df_list, ignore_index=True)

    all_curves = [gr_col, cgr_col, den_col, cnl_col, ac_col, pe_col, layer_col]
    for col in all_curves:
        if col in combined_df.columns and col != layer_col:
            combined_df[col] = pd.to_numeric(combined_df[col], errors='coerce')
    combined_df.replace([-99999.0, -9999.0, -999.25], np.nan, inplace=True)

    core_curves_for_dropna = [gr_col, den_col, cnl_col, ac_col, layer_col]
    combined_df.dropna(subset=core_curves_for_dropna, inplace=True)
    print(f"数据加载和预处理完成，共 {len(combined_df)} 条有效数据点。")
    return combined_df


def create_intelligence_briefing(df: pd.DataFrame, params: Dict) -> Dict:
    curve_names = _get_curves(params)
    gr_col, cgr_col, den_col, cnl_col, ac_col, layer_col = (
        curve_names["GR"], curve_names["CGR"], curve_names["DEN"],
        curve_names["CNL"], curve_names["AC"], curve_names["LAYER"]
    )

    briefing = {"data_point_count": len(df)}
    curves_to_brief = [gr_col, cgr_col, den_col, cnl_col, ac_col]
    for curve in curves_to_brief:
        if curve in df.columns:
            series = df[curve].dropna()
            if not series.empty:
                briefing[f"{curve}_stats"] = {
                    'min': round(series.min(), 3),
                    'p10': round(series.quantile(0.10), 3),
                    'p50_median': round(series.median(), 3),
                    'p90': round(series.quantile(0.90), 3),
                    'max': round(series.max(), 3),
                    'mean': round(series.mean(), 3),
                    'std_dev': round(series.std(), 3)
                }

    if gr_col in df.columns and df[gr_col].notna().any():
        gr_series = df[gr_col].dropna()
        if not gr_series.empty and gr_series.max() > gr_series.min():
            hist, bin_edges = np.histogram(gr_series, bins=10, range=(gr_series.min(), gr_series.max()))
            if hist.sum() > 0:
                briefing['GR_histogram'] = {
                    "bins": [f"{bin_edges[i]:.1f}-{bin_edges[i+1]:.1f}" for i in range(10)],
                    "counts_percent": (hist / hist.sum() * 100).round(1).tolist()
                }

    if den_col in df.columns and cnl_col in df.columns and df[den_col].notna().any() and df[cnl_col].notna().any():
        cross_plot_df = df[[den_col, cnl_col]].dropna()
        if len(cross_plot_df) > 10:
            briefing['DEN_CNL_crossplot'] = {
                "correlation_coefficient": round(cross_plot_df[den_col].corr(cross_plot_df[cnl_col]), 3)
            }
    return briefing


def get_expert_decision(advisor_agent, briefing: Dict, layer_name: str, few_shot_examples: list) -> Tuple[Dict, str]:
    briefing_str = json.dumps(briefing, indent=2, ensure_ascii=False)
    prompt = f"""
    地层 '{layer_name}' 的地质情报简报如下:
    {briefing_str}

    请根据你在System Prompt中学到的决策原则和输出格式要求，为该地层返回最终的解释策略JSON。
    """
    try:
        print("    - -> 调用 InterpretationAdvisorAgent 进行综合决策...")
        raw_response = advisor_agent.generate_response(user_input=prompt, few_shot_examples=few_shot_examples)
        cleaned_response = extract_json_from_response(raw_response)
        final_decision = json.loads(cleaned_response)
        print(f"    - -> Agent 决策完成. 推荐模型: {final_decision.get('best_model_type', 'N/A')}")
        return final_decision, f"Success: Strategy generated by Agent. Recommended: {final_decision.get('best_model_type', 'N/A')}."
    except Exception as e:
        cleaned_str = extract_json_from_response(raw_response) if 'raw_response' in locals() else "N/A"
        return None, f"Error: Agent workflow failed. Details: {e}. Cleaned response was: '{cleaned_str}'"


def build_strategy(config: Dict, project_root: Path) -> Dict:
    print("\n===== 启动工具: shale_build_strategy =====")
    paths = config["paths"]
    params = config.get("parameters", {})

    data_directory = paths["data_directory"]
    output_directory = paths["output_directory"]
    agent_config = paths["agent_config"]
    baseline_config = paths.get("baseline_config")
    strategy_filename = params.get("strategy_filename", "shale_interpretation_strategy_agent.json")
    output_path = os.path.join(output_directory, strategy_filename)

    ensure_dirs(output_directory)

    curve_names = _get_curves(params)
    gr_col = curve_names["GR"]
    layer_col = curve_names["LAYER"]
    rho_f_water = params.get("rho_f_water", 1.0)
    rho_ma_sand = params.get("rho_ma_sand", 2.65)
    universal_default_params = params.get("universal_default_params", {
        'gr_min': 30.0, 'gr_max': 150.0, 'rho_sh': 2.55,
        'nphi_sh': 35.0, 'delta_t_sh': 320.0, 'optimized_gcur': 2.0
    })
    use_few_shot = params.get("use_few_shot", False)

    master_df = load_and_preprocess_data(data_directory, params)

    print("\n--- 步骤2: 开始使用Agent构建解释策略---")
    print("  - 正在初始化LLM Agent...")
    advisor_agent = load_agent(agent_config, project_root)
    print("  - Agent 初始化成功.")

    grouped = master_df.groupby(layer_col)
    formation_strategies = {}
    quality_report = {}
    few_shot_examples = []

    if use_few_shot and baseline_config and os.path.exists(baseline_config):
        print("  - Few-Shot学习已启用。正在构建动态专家范例...")
        try:
            with open(baseline_config, 'r', encoding='utf-8') as f:
                baseline_config_data = json.load(f)
        except Exception as e:
            print(f"  - 警告: 加载基准配置失败: {e}")
            baseline_config_data = None

        if baseline_config_data:
            example_layers = ['J1f', 'chang7', 'chang10']
            for layer in example_layers:
                if layer in baseline_config_data.get('formation_strategies', {}) and layer in grouped.groups:
                    layer_df = grouped.get_group(layer)
                    briefing = create_intelligence_briefing(layer_df, params)
                    briefing_str = json.dumps(briefing, indent=2, ensure_ascii=False)
                    user_content = f"地质情报简报 for '{layer}':\n{briefing_str}\n请根据你在System Prompt中学到的决策原则和输出格式要求，为该地层返回最终的解释策略JSON。"
                    assistant_answer = baseline_config_data['formation_strategies'][layer]
                    reasoning_map = {
                        'J1f': "GR直方图呈清晰双峰，表明砂泥岩端点分明，适合伽马类模型。DEN-CNL负相关性强，但未见极端异常，故优先选择压实校正的Larionov模型。参数以P10/P90为基准微调得到。",
                        'chang7': "GR值整体极高且分布宽，提示存在放射性异常的高伽马砂岩。此时伽马模型不可靠，必须采用不受放射性影响的中子-密度交会法。",
                        'chang10': "GR直方图呈较窄的单峰，DEN-CNL相关性几乎为零，表明岩性相对简单，无明显放射性影响。在这种情况下，最简单、最稳健的线性模型是最佳选择。"
                    }
                    assistant_answer_cleaned = {
                        "best_model_type": assistant_answer["best_model_type"],
                        "final_optimized_params": assistant_answer["final_optimized_params"],
                        "reasoning": reasoning_map.get(layer, "")
                    }
                    assistant_content = json.dumps(assistant_answer_cleaned, indent=2, ensure_ascii=False)
                    few_shot_examples.append({"role": "user", "content": user_content})
                    few_shot_examples.append({"role": "assistant", "content": assistant_content})
            print(f"  - 成功构建了 {len(few_shot_examples)//2} 个专家范例。")
            if few_shot_examples:
                few_shot_path = os.path.join(output_directory, 'generated_few_shot_examples.json')
                with open(few_shot_path, 'w', encoding='utf-8') as f:
                    json.dump(few_shot_examples, f, indent=2, ensure_ascii=False)
                print(f"  - Few-Shot 范例已成功保存至: {os.path.abspath(few_shot_path)}")
    else:
        print("  - Few-Shot学习已禁用。Agent将以Zero-Shot模式运行。")

    for layer_name, layer_df in grouped:
        print(f"\n  - 正在分析地层: {layer_name}...")
        if len(layer_df) < 100:
            status = "Skipped: Insufficient data points"
            strategy = {'best_model_type': 'N/A', 'reasoning_from_agent': status}
        else:
            briefing = create_intelligence_briefing(layer_df, params)
            strategy, status = get_expert_decision(advisor_agent, briefing, layer_name, few_shot_examples)

        if strategy is None:
            print(f"    - 诊断: {status}")
            print(f"    - -> 启用全局后备策略...")
            strategy = {
                'best_model_type': 'Linear',
                'reasoning_from_agent': 'Agent workflow failed, falling back to universal default.',
                'final_optimized_params': universal_default_params
            }
            status += " -> Used Universal Default."

        formation_strategies[layer_name] = strategy
        quality_report[layer_name] = status

    final_config = {
        "project_info": {
            "description": "Auto-generated interpretation strategy by LLM Agents.",
            "generation_date": datetime.now().strftime("%Y-%m-%d"),
            "few_shot_enabled": use_few_shot,
            "data_quality_report": quality_report
        },
        "global_parameters": {"rho_f_water": rho_f_water, "rho_ma_sand": rho_ma_sand},
        "formation_strategies": formation_strategies
    }

    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(final_config, f, indent=2, ensure_ascii=False)
    print(f"\n--- 成功！由Agent生成的解释策略文件已保存到: {output_path} ---")

    return {
        "success": True,
        "output_files": [output_path],
        "message": f"Shale strategy built for {len(formation_strategies)} formations."
    }


def run_interpretation(config: Dict, project_root: Path) -> Dict:
    print("\n===== 启动工具: shale_run_interpretation =====")
    paths = config["paths"]
    params = config.get("parameters", {})

    data_directory = paths["data_directory"]
    strategy_file = paths["strategy_file"]
    output_directory = paths["output_directory"]
    output_subfolder = params.get("output_subfolder", "interpreted_wells")
    curve_names = _get_curves(params)

    gr_col, cgr_col, den_col, cnl_col, ac_col, pe_col, layer_col, sh_col = (
        curve_names["GR"], curve_names["CGR"], curve_names["DEN"],
        curve_names["CNL"], curve_names["AC"], curve_names["PE"],
        curve_names["LAYER"], curve_names["SH"]
    )
    rho_ma_sand = params.get("rho_ma_sand", 2.65)
    rho_f_water = params.get("rho_f_water", 1.0)
    few_shot_suffix = params.get("few_shot_suffix", "_with_fewshot")
    zero_shot_suffix = params.get("zero_shot_suffix", "_zero_shot")

    ensure_dirs(output_directory)

    print("--- 步骤1: 加载单井数据与解释策略 ---")
    all_files = glob.glob(os.path.join(data_directory, '*.txt'))
    if not all_files:
        raise FileNotFoundError(f"数据目录 '{data_directory}' 中未找到txt文件。")

    well_data_dict = {}
    for f in all_files:
        try:
            well_name = os.path.splitext(os.path.basename(f))[0]
            df = pd.read_csv(f, header=0, skiprows=[1], sep=',')
            df['LOG_ID_FROM_FILENAME'] = well_name
            well_data_dict[well_name] = df
        except Exception as e:
            print(f"  - 警告: 读取文件 {os.path.basename(f)} 失败: {e}")

    if not well_data_dict:
        raise ValueError("未能成功读取任何测井文件。")

    with open(strategy_file, 'r', encoding='utf-8') as f:
        strategy = json.load(f)
    print(f"成功加载Agent生成的解释策略文件: {strategy_file}")
    few_shot_enabled = strategy.get("project_info", {}).get("few_shot_enabled", False)
    print(f"  - 策略生成模式: {'Few-Shot' if few_shot_enabled else 'Zero-Shot'}")

    interpreted_well_dict = {}
    for well_name, well_df in well_data_dict.items():
        print(f"\n--- 正在解释井: {well_name} ---")
        interpreted_df = _run_shale_interpretation(
            well_df, strategy, curve_names,
            rho_ma_sand, rho_f_water
        )
        interpreted_well_dict[well_name] = interpreted_df

    final_df_all_wells = pd.concat(interpreted_well_dict.values())
    validated_df = _validate_and_report(
        final_df_all_wells, few_shot_enabled,
        curve_names, output_directory, few_shot_suffix, zero_shot_suffix
    )

    for well_name, group in validated_df.groupby('LOG_ID_FROM_FILENAME'):
        if well_name in interpreted_well_dict:
            interpreted_well_dict[well_name] = group

    exported_files = _export_results_per_well(
        interpreted_well_dict, output_directory, output_subfolder
    )

    return {
        "success": True,
        "output_files": exported_files,
        "message": f"Shale interpretation completed for {len(interpreted_well_dict)} wells."
    }


def _run_shale_interpretation(df: pd.DataFrame, strategy: Dict, curve_names: Dict,
                              rho_ma_sand: float, rho_f_water: float) -> pd.DataFrame:
    gr_col, cgr_col, den_col, cnl_col, layer_col, sh_col = (
        curve_names["GR"], curve_names["CGR"], curve_names["DEN"],
        curve_names["CNL"], curve_names["LAYER"], curve_names["SH"]
    )

    df_interpreted = df.copy()
    all_possible_curves = [gr_col, cgr_col, den_col, cnl_col, sh_col, layer_col]
    for col in all_possible_curves:
        if col in df_interpreted.columns:
            if col != layer_col:
                df_interpreted[col] = pd.to_numeric(df_interpreted[col], errors='coerce')
        else:
            df_interpreted[col] = np.nan

    if df_interpreted[layer_col].isnull().all():
        print(f"  - 致命错误: 关键列 '{layer_col}' 所有值均为空。")
        df_interpreted['interpretation_status'] = 'Failed_Invalid_Layer_Column'
        return df_interpreted

    df_interpreted[layer_col] = df_interpreted[layer_col].astype(str).str.strip().replace("nan", "未定义")
    df_interpreted.replace([-99999.0, -9999.0, -999.25], np.nan, inplace=True)
    df_interpreted['interpretation_status'] = 'Success'

    results_list = []
    for layer_name, group in df_interpreted.dropna(subset=[layer_col]).groupby(layer_col):
        group_copy = group.copy()
        if layer_name in strategy.get('formation_strategies', {}):
            layer_strategy = strategy['formation_strategies'][layer_name]
            params = layer_strategy.get('final_optimized_params')
            model_type = layer_strategy.get('best_model_type')

            if not params or not model_type:
                group_copy['interpretation_status'] = 'Failed_Incomplete_Strategy'
                results_list.append(group_copy)
                continue

            source_curve, min_param, max_param = gr_col, 'gr_min', 'gr_max'
            if 'CGR' in model_type and cgr_col in group_copy and group_copy[cgr_col].notna().any():
                source_curve, min_param, max_param = cgr_col, 'cgr_min', 'cgr_max'
                print(f"  - 地层 {layer_name}: 应用CGR策略。")

            igr = (group_copy[source_curve] - params.get(min_param, 30)) / (
                params.get(max_param, 150) - params.get(min_param, 30)
            )
            group_copy['vsh_Linear'] = igr.clip(0, 1)
            group_copy['vsh_Larionov_Optimized'] = (
                np.power(2, params.get('optimized_gcur', 2.0) * igr.clip(0, 1)) - 1
            ) / (np.power(2, params.get('optimized_gcur', 2.0)) - 1)
            group_copy['vsh_Clavier'] = (
                1.7 - np.sqrt(np.maximum(0, 3.38 - (igr + 0.7)**2))
            ).clip(0, 1)

            nphi_sh_param = params.get('nphi_sh', 35.0) * (100 if params.get('nphi_sh', 35.0) < 1.5 else 1)
            dphi = (rho_ma_sand - group_copy[den_col]) / (rho_ma_sand - rho_f_water)
            nphi = group_copy[cnl_col] / 100.0
            denominator = (nphi_sh_param / 100.0 - dphi)
            vsh_nd = (nphi - dphi) / denominator.where(denominator.abs() > 1e-6)
            group_copy['vsh_Neutron_Density'] = vsh_nd.clip(0, 1)

            final_model_col_name = f"vsh_{model_type.replace('CGR_', '')}"
            if final_model_col_name in group_copy:
                vsh_base = group_copy[final_model_col_name]
                is_radioactive_sand = (vsh_base - group_copy['vsh_Neutron_Density'] > 0.3) & (
                    group_copy['vsh_Neutron_Density'].notna()
                )
                group_copy['vsh_final'] = np.where(
                    is_radioactive_sand, group_copy['vsh_Neutron_Density'], vsh_base
                )
            else:
                group_copy['vsh_final'] = np.nan
        else:
            group_copy['interpretation_status'] = 'Failed_No_Strategy'

        results_list.append(group_copy)

    if not results_list:
        return df_interpreted

    final_df = pd.concat(results_list).sort_index()
    final_df = df_interpreted.drop(columns=final_df.columns.tolist(), errors='ignore').join(final_df)
    print("  - 标准化解释计算完成。")
    return final_df


def _validate_and_report(df_all_wells: pd.DataFrame, few_shot_enabled: bool,
                         curve_names: Dict, output_directory: str,
                         few_shot_suffix: str, zero_shot_suffix: str) -> pd.DataFrame:
    print("\n--- 步骤3: 最终精度评估与报告 ---")
    sh_col = curve_names["SH"]
    layer_col = curve_names["LAYER"]
    df_copy = df_all_wells.copy()
    df_copy[sh_col] = pd.to_numeric(df_copy[sh_col], errors='coerce')
    df_copy['vsh_final'] = pd.to_numeric(df_copy['vsh_final'], errors='coerce')

    is_percent = df_copy[sh_col].dropna().quantile(0.95, interpolation='lower') > 1.5 if not df_copy[sh_col].dropna().empty else False
    df_copy['sh_frac'] = df_copy[sh_col] / 100.0 if is_percent else df_copy[sh_col]
    reasonable_mask = (df_copy['sh_frac'] >= 0) & (df_copy['sh_frac'] <= 1.5)
    df_clean = df_copy[reasonable_mask].dropna(subset=['vsh_final', 'sh_frac'])

    if df_clean.empty:
        print("警告: 无有效数据点可供评估。")
        return df_copy

    df_clean['abs_diff'] = (df_clean['vsh_final'] - df_clean['sh_frac']).abs()
    mae = df_clean['abs_diff'].mean()
    df_clean['error_rate'] = df_clean.apply(
        lambda row: row['abs_diff'] / row['sh_frac'] if row['sh_frac'] != 0 else row['abs_diff'],
        axis=1
    )
    mean_error_rate = df_clean['error_rate'].mean() * 100

    print(f"平均绝对误差（MAE）: {mae:.4f}")
    print(f"平均误差率: {mean_error_rate:.2f}%")

    report_lines = ["--- 全局评估报告 ---", f"(MAE): {mae}", "\n--- 分层评估报告 ---"]
    print("\n--- 全局评估报告 ---")
    print(f"(MAE): {mae}")
    print("\n--- 分层评估报告 ---")
    for layer_name, group in df_clean.groupby(layer_col):
        layer_mae = group['abs_diff'].mean()
        layer_line = f"  - 地层 '{layer_name}': MAE = {layer_mae*100:.2f}%"
        print(layer_line)
        report_lines.append(layer_line)

    suffix = few_shot_suffix if few_shot_enabled else zero_shot_suffix
    report_filename = f'evaluation_summary_report{suffix}.txt'
    report_path = os.path.join(output_directory, report_filename)
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(report_lines))
    print(f"\n评估总结报告已成功保存至: {os.path.abspath(report_path)}")

    df_copy['abs_diff'] = (df_copy['vsh_final'] - df_copy['sh_frac']).abs()
    return df_copy


def _export_results_per_well(well_data_dict: Dict[str, pd.DataFrame],
                             output_directory: str, output_subfolder: str) -> list:
    print("\n--- 步骤4: 导出分井解释成果 ---")
    output_dir = os.path.join(output_directory, output_subfolder)
    ensure_dirs(output_dir)
    success_count, failed_count, exported_files_count = 0, 0, 0
    exported_files = []
    for well_name, df in well_data_dict.items():
        if 'interpretation_status' in df.columns and (df['interpretation_status'] == 'Failed_Invalid_Layer_Column').any():
            failed_count += 1
            continue
        success_count += 1
        try:
            output_path = os.path.join(output_dir, f"{well_name}_shale_interpreted.csv")
            df.to_csv(output_path, index=False, encoding='utf-8-sig')
            exported_files.append(output_path)
            exported_files_count += 1
        except Exception as e:
            print(f"  - 警告: 导出井 {well_name} 时发生错误: {e}")
    print(f"\n--- 导出总结 ---\n  - 成功解释井数: {success_count}\n  - 失败解释井数: {failed_count}\n  - 最终导出文件数: {exported_files_count}\n  - 成果保存在目录: {os.path.abspath(output_dir)}")
    return exported_files
